# Generated by Django 2.2.4 on 2020-01-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_one', '0002_auto_20200118_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pic',
            new_name='profile',
        ),
    ]
